### ISSUE TITLE
Foods have twice as much saturation as expected

### ISSUE THREAD

**Issue by bones-01** [Additional-Mods/additionaladditions#104] opened 2023-01-20 21:35 UTC
I felt that the honeyed apple was a bit overpowered in my game, as it gave 13 full bars of saturation (26ish points) and it looks like based on the numbers in the code it's supposed to be half that, 8*1.6.  I checked the values of all the other foods with appleskin and compared them to the values in the code and they all also seem to give twice as much saturation as expected.

**Comment by bones-01** [comment] 2023-01-20 21:39
![image_2023-01-20_163945373](https://user-images.githubusercontent.com/64933783/213809998-b6264ee3-c6a8-412e-af81-12a6f2393d8c.png)

**Comment by Dqu1J** [comment] 2023-01-26 03:06
duplicate of #70

**Closed by Dqu1J** 2023-01-26 03:06 UTC
