### ISSUE TITLE
Blocks rendered wrongly when joining a bungeecord server

### ISSUE THREAD

**Issue by 5ur3z** [Additional-Mods/additionaladditions#97] opened 2022-12-01 00:31 UTC
When I join my BungeeCord Server (Spigot) with this mod loaded, all the blocks rendered wrongly.

![image](https://user-images.githubusercontent.com/89332189/204936826-7b1f0927-86b1-49bb-a29c-b8e0f235557e.png)
![image](https://user-images.githubusercontent.com/89332189/204937084-29829239-7e63-416e-af02-b8b6fed8aa9a.png)

**Comment by Dqu1J** [comment] 2022-12-02 12:24
duplicate of #92

**Closed by Dqu1J** 2022-12-02 12:24 UTC
