### ISSUE TITLE
[Suggestion] An alternative mode for a more balanced watering can?

### ISSUE THREAD

**Issue by Rimevel** [Additional-Mods/additionaladditions#50] opened 2022-05-08 18:27 UTC
Right now the watering can pretty much make bone meal obsolete. All you need is some copper ingots, a bucket, and an infinite water source to have virtually infinite bone meal.

My suggestion is to have a config option that make the watering can have to be reloaded with bone meal after the water is refilled. Maybe by crafting it together with some bone meal?

This would essentially make the watering can a way to get more uses out of bone meal instead of replacing it.

**Comment by Dqu1J** [comment] 2023-02-19 01:48
duplicate of #78

**Closed by Dqu1J** 2023-02-19 01:48 UTC
Labels: enhancement, low priority, nice
